name: Static Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Install musl dependencies
        run: sudo apt-get update && sudo apt-get install -y musl musl-dev
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl
      - name: Build Artifact
        run: cargo build --release --locked --target x86_64-unknown-linux-musl
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Latest Build
          path: target/x86_64-unknown-linux-musl/release/${{ github.event.repository.name }}
