name: Static Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --version 0.2.114
      - name: Install musl dependencies
        run: sudo apt-get update && sudo apt-get install -y musl musl-dev
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl, wasm32-unknown-unknown
      
      - name: Build Frontend
        run: cargo build -p recordbox-ui --release --locked --target wasm32-unknown-unknown
      - name: Bind WASM
        run: wasm-bindgen --out-dir frontend/pkg --target web target/wasm32-unknown-unknown/release/recordbox_ui.wasm
      - name: Optimize WASM
        uses: JohannesDeml/binaryen-wasm-opt@v1
        with:
          file: frontend/pkg/recordbox_ui_bg.wasm
          options: -Oz -all --fast-math

      - name: Build Backend
        run: cargo build -p recordbox --release --locked --target x86_64-unknown-linux-musl
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: artifact
          path: target/x86_64-unknown-linux-musl/release/${{ github.event.repository.name }}
